CREATE TABLE IF NOT EXISTS `wx_session` (
    `id` INT UNSIGNED AUTO_INCREMENT,
    `openid` VARCHAR(80) NOT NULL,
    `session_key` VARCHAR(80) NOT NULL,
    `unionid` VARCHAR(80) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY (`openid`)
)